/** UI strings. English only for now; keep every visible label here so it can be translated later. */
export const ui = {
  appTitle: 'Sentrax interactive RTLS demo',
  brandName: 'Sentrax',
  simulatedData: 'Simulated data',
  cta: {
    bookMeeting: 'Book a meeting',
    exploreDemo: 'Explore the interactive demo',
    exploreFreely: 'Explore freely',
    newTabHint: 'opens in a new tab',
  },
  scenes: {
    hospital: 'Hospital',
    warehouse: 'Warehouse and Manufacturing',
  },
  loading: {
    label: 'Loading scene',
    percent: (p: number) => `${Math.round(p)} percent`,
  },
  placeholderStage: {
    title: 'Scene preview',
    body: 'Setup build. The hospital and warehouse scenes arrive in later milestones.',
  },
  fallback: {
    title: 'This demo needs WebGL2',
    body: 'Your browser or device cannot display the interactive 3D view. You can still talk to us about real-time location for your hospital, warehouse or production site.',
  },
  simDebug: {
    title: 'Simulation debug view',
    scene: 'Scene',
    seed: 'Seed',
    time: 'Time',
    speed: 'Speed',
    pause: 'Pause',
    play: 'Play',
    reset: 'Reset',
    layers: 'Layers',
    layerNames: {
      truth: 'Ground truth',
      rssi: 'RSSI estimate',
      aoa: 'AoA estimate',
      bilink: 'BiLink rooms and relays',
      hybrid: 'Hybrid report',
      errors: 'Error lines',
      nav: 'Navigation graph',
      labels: 'Labels',
    },
    stats: 'Accuracy against ground truth, last 30 s',
    rssiMedian: 'RSSI median error',
    aoaMedian: 'AoA median error (inside coverage)',
    bilinkCorrect: 'BiLink correct room (tags still for 6 s or more)',
    events: 'Events',
    alerts: 'Active alerts',
    scenarios: 'Scenarios',
    none: 'None',
    selected: 'Selected tag',
    clickHint: 'Click near a tag to inspect it.',
    legend:
      'Black dot: true position. Blue: RSSI. Pink: AoA. Violet: BiLink room and relay. Ring: hybrid report.',
    sceneNames: {
      hospital: 'Hospital',
      warehouse: 'Warehouse and Manufacturing',
      'test-rssi': 'Test layout: RSSI hall',
      'test-aoa': 'Test layout: AoA area',
      'test-bilink': 'Test layout: BiLink rooms',
      'test-dock': 'Test layout: dock door',
    },
  },
  dev: {
    claimsTitle: 'Unapproved content',
    claimsEmpty: 'All claims are approved.',
    claimsToggle: 'Claims',
    brandPlaceholderWarning:
      'Brand tokens are placeholders. They are not Sentrax colors or fonts yet. Run npm run brand:extract once sentrax.com is reachable.',
  },
} as const;
